### ISSUE TITLE
argument after ** must be a mapping, not YoufoneItem

### ISSUE THREAD

**Issue by SpeedlimitsB** [geertmeersman/youfone#106]
HA: Latesed

_**Getting this error all the time . i did a reconfig but still same issue :**_

2024-01-16 19:23:09.009 ERROR (MainThread) [custom_components.youfone] Unexpected error fetching youfone data: custom_components.youfone.models.YoufoneItem() argument after ** must be a mapping, not YoufoneItem
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/youfone/__init__.py", line 122, in _async_update_data
    self.data = {key: YoufoneItem(**value) for key, value in self.data.items()}
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/youfone/__init__.py", line 122, in <dictcomp>
    self.data = {key: YoufoneItem(**value) for key, value in self.data.items()}
                      ^^^^^^^^^^^^^^^^^^^^
TypeError: custom_components.youfone.models.YoufoneItem() argument after ** must be a mapping, not YoufoneItem

**Comment by geertmeersman** [comment]
Did you try it with the last version? As I fixed it recently

**Comment by geertmeersman** [comment]
0.6.0 but perhaps you need to redownload it
