### ISSUE TITLE
Youfone integration not working anymore

### ISSUE THREAD

**Issue by coldburn89** [geertmeersman/youfone#170]
[Youfone debug.txt](https://github.com/user-attachments/files/17265738/Youfone.debug.txt)

After latest Home Assistant update the Youfone integration has broken.

Home Assistant Supervisor: 2024.09.1
Home Assistant Core: 2024.10.1
Home Assistant OS: 13.1

Debug logging:

AttributeError: 'str' object has no attribute 'get'
2024-10-05 11:07:08.437 DEBUG (MainThread) [custom_components.youfone.sensor] [sensor|async_setup_entry|async_add_entities|start]
2024-10-05 11:07:08.438 DEBUG (MainThread) [custom_components.youfone.sensor] Searching for customer-customer
2024-10-05 11:07:08.438 DEBUG (MainThread) [custom_components.youfone.sensor] Searching for sim_only-sim_subscription
2024-10-05 11:07:08.438 DEBUG (MainThread) [custom_components.youfone.sensor] Searching for sim_only-sim_subscription_price
2024-10-05 11:07:08.438 DEBUG (MainThread) [custom_components.youfone.sensor] Searching for sim_only-data
2024-10-05 11:07:08.438 DEBUG (MainThread) [custom_components.youfone.sensor] Searching for sim_only-remaining_days
2024-10-05 11:07:08.438 DEBUG (MainThread) [custom_components.youfone.sensor] Searching for sim_only-voice
2024-10-05 11:07:32.866 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7f02da1aa0d0>,) inside the event loop by custom integration 'youfone' at custom_components/youfone/config_flow.py, line 60: profile = await client.login() (offender: /usr/local/lib/python3.12/site-packages/httpx/_config.py, line 149: context.load_verify_locations(cafile=cafile)), please create a bug report at https://github.com/geertmeersman/youfone/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 556, in start
    task = asyncio.Task(coro, loop=loop, eager_start=True)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle
    return await handler(request)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 285, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 370, in async_configure
    result = await self._async_configure(flow_id, user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 417, in _async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 520, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
  File "/config/custom_components/youfone/config_flow.py", line 169, in async_step_username_password
    test = await self.test_connection(user_input)
  File "/config/custom_components/youfone/config_flow.py", line 115, in test_connection
    profile = await self.async_validate_input(user_input)
  File "/config/custom_components/youfone/config_flow.py", line 60, in async_validate_input
    profile = await client.login()

2024-10-05 11:07:33.104 DEBUG (MainThread) [custom_components.youfone.sensor] [sensor|async_setup_entry|async_add_entities|start]
2024-10-05 11:07:33.104 DEBUG (MainThread) [custom_components.youfone.sensor] Searching for customer-customer
2024-10-05 11:07:33.104 DEBUG (MainThread) [custom_components.youfone.sensor] Searching for sim_only-sim_subscription
2024-10-05 11:07:33.104 DEBUG (MainThread) [custom_components.youfone.sensor] Searching for sim_only-sim_subscription_price
2024-10-05 11:07:33.104 DEBUG (MainThread) [custom_components.youfone.sensor] Searching for sim_only-data
2024-10-05 11:07:33.104 DEBUG (MainThread) [custom_components.youfone.sensor] Searching for sim_only-remaining_days
2024-10-05 11:07:33.104 DEBUG (MainThread) [custom_components.youfone.sensor] Searching for sim_only-voice
2024-10-05 11:07:35.931 WARNING (SyncWorker_61) [py.warnings] /usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.20.100'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

**Comment by coldburn89** [comment]
Hi Geert,

Still doesn't work on the beta version. I enabled debug logging and will
upload later tomorrow morning.

Met vriendelijke groet,

Aaron van den Aker

**Comment by geertmeersman** [comment]
You will probably need to remove the /config/.storage/youfone folder

**Comment by geertmeersman** [comment]
Try with this one: https://github.com/geertmeersman/youfone/releases/tag/v0.12.3-beta.6

**Comment by coldburn89** [comment]
Hi Geert, the latest beta version you send me works like a charm! Do you
need any more information from me?

Regards Aaron

**Comment by geertmeersman** [comment]
No, I'll merge the pull request and build a new release 👍
Thanks for testing and reporting

**Comment by geertmeersman** [comment]
Release published
