### ISSUE TITLE
Cannot setup integration

### ISSUE THREAD

**Issue by magtimmermans** [geertmeersman/youfone#48]
Thank you for this integration. But unfortunately it doesn't let me add it. 

**Describe the bug**
Try to add to add the integration. Using my username and password. And select Netherlands. Then press save and then it shows unknown error. I cannot find anything in the logfile

**Expected behavior**
I expect that the integration will be added.

`

2023-07-13 22:26:11.217 DEBUG (SyncWorker_1) [custom_components.youfone.client] [YoufoneClient|login|start]
2023-07-13 22:26:11.217 DEBUG (SyncWorker_1) [custom_components.youfone.client] [YoufoneClient|login|authenticate] Calling POST https://my.youfone.nl/prov/MyYoufone/MyYOufone.Wcf/v2.0/Service.svc/json/login with {"request": {"Login": "name@domain.nl", "Password": "*************"}}
2023-07-13 22:26:11.256 DEBUG (MainThread) [custom_components.youfone.config_flow] ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

`

**Comment by geertmeersman** [comment]
Hi Mag, possibly it was a temporary issue @ Youfone side, can you check again?
And if not, please reach out on the discord

**Comment by Tazzios** [comment]
I currently had i already setup but currently also have a connection aborted error.  Login in on the website still works.

**Comment by geertmeersman** [comment]
Seems it's linked to the python requests library. I'm trying to find a solution, but none found yet...
For some reason, the server @ Youfone is closing the socket, perhaps linked to some TLS requirements.
When I call the NL server using Curl, all goes fine (as it is done in the browser).

**Comment by geertmeersman** [comment]
Ok, I have tried to set up the connection using pycurl and this seems to work (perhaps something server side @ youfone).
Will try to build it in asap in the integration

**Comment by geertmeersman** [comment]
Can you try with this beta: https://github.com/geertmeersman/youfone/releases/tag/v0.3.9-beta.1
Should be visible in HACS if you enable beta versions

**Comment by magtimmermans** [comment]
Hi,

I can login but no data will be retrieved.

`
2023-07-15 14:21:47.033 DEBUG (SyncWorker_5) [custom_components.youfone.client] [YoufoneClient|login|authenticate] http status code = 200 (expecting 200)
2023-07-15 14:21:47.035 ERROR (MainThread) [custom_components.youfone] Unexpected error fetching youfone data: object of type 'bool' has no len()
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
self.data = await self._async_update_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/youfone/__init__.py", line 107, in _async_update_data
if items is not None and len(items) > 0:
^^^^^^^^^^
TypeError: object of type 'bool' has no len()
2023-07-15 14:21:47.036 DEBUG (MainThread) [custom_components.youfone] Finished fetching youfone data in 0.075 seconds (success: False)
`
I must mention that I have a pre-paid card.

**Comment by dennidoubles** [comment]
Got the same issues, can't add the integration after downloading the latest bèta (v0.3.9-beta.15)

**Comment by Tazzios** [comment]
v0.3.9-beta.15 works for me. 👍 

Different is maybe that I already had the addon running?

**Comment by geertmeersman** [comment]
> v0.3.9-beta.15 works for me. 👍 
> 
> Different is maybe that I already had the addon running?

Shouldn't really make a difference. But good news it works. Which means that for the others it's probably linked to some features missing in the code. We'll sort it out, but please all join on discord, as this eases the communication and debugging

**Comment by magtimmermans** [comment]
Still same issue. I will try send some more info when i have more time.

**Comment by stephansande** [comment]
I have the same error as described in the first post.

Systeem 2023.7.3
HACS:  1:32.1

website and youfone app both respond well. Both on pc as android phone.

**Comment by Tazzios** [comment]
Unfortunately the problem indeed seems to be back, for me also no data anymore.
