### ISSUE TITLE
Youfone integration cannot start - exception expection value

### ISSUE THREAD

**Issue by rgerbranda** [geertmeersman/youfone#57]
Since the last update of Home Assistant, the following error is in the logs. 

```2023-07-29 12:37:52.913 WARNING (MainThread) [homeassistant.config_entries] Config entry 'x@y.nl' for youfone integration not ready yet: Exception Expecting value: line 1 column 1 (char 0); Retrying in background```

Home Assistant 2023.7.3
Youfone integration 0.4.2

**Comment by rgerbranda** [comment]
I tried to remove the configuration and re-add it. But that gives "Onverwachte fout" in the GUI.

**Comment by rgerbranda** [comment]
Hi, I cannot add the integration anymore. So I cannot enable debugging. I enabled general Home Assistant debuging, but found no Youfone related errors.

**Comment by geertmeersman** [comment]
Hi, you can enable this in the configuration.yaml:

```
logger:
  default: warning
  logs:
    custom_components.youfone: debug
```

**Comment by Evergorn** [comment]
I have a similar issue. I am trying to log in using Nieuwe Youfone account it gives an unexpected error. I can log in youfone's website.

**Comment by geertmeersman** [comment]
Please put  the above logger configuration in place and this will then help me  to discover what's going on :-)

**Comment by Evergorn** [comment]
> Please put the above logger configuration in place and this will then help me to discover what's going on :-)

I have added the logger configuration. No errors in configuration. Where can I find the logbook you need?

**Comment by rgerbranda** [comment]
Hi, I put default on debug. To my opinion youfone should be included then, but no results.

**Comment by Evergorn** [comment]
I have the log in which youfone is mentioned. Also my login and password are mentioned. Is it enough if I remove them?

**Comment by geertmeersman** [comment]
Yes, just remove your credentials from the log

**Comment by Evergorn** [comment]
> Yes, just remove your credentials from the log

I am sorry for the delay but I had some other things to do.
I am not familiar with Github protocols. Can I post the log or somewhere else?

**Comment by rgerbranda** [comment]
Hi @geertmeersman 

Here is the log:

```
2023-08-17 21:47:36.079 DEBUG (SyncWorker_5) [custom_components.youfone.client] [YoufoneClient|login|start]
2023-08-17 21:47:36.192 DEBUG (SyncWorker_5) [custom_components.youfone.client] [YoufoneClient|login|authenticate] Calling POST https://my.youfone.nl/prov/MyYoufone/MyYOufone.Wcf/v2.0/Service.svc/json/login with {"request": {"Login": "me@abc.xyz.nl", "Password": "xx"}}
2023-08-17 21:47:36.348 DEBUG (SyncWorker_5) [custom_components.youfone.client] [YoufoneClient|login|authenticate] http status code = 418 (expecting None)
2023-08-17 21:47:36.348 DEBUG (SyncWorker_5) [custom_components.youfone.client] [YoufoneClient|login|authenticate] Response:

2023-08-17 21:47:36.349 DEBUG (MainThread) [custom_components.youfone.config_flow] Expecting value: line 1 column 1 (char 0)
```

**Comment by Evergorn** [comment]
Here is my log.
ZeroDivisionError: division by zero
2023-08-16 12:06:44.067 DEBUG (SyncWorker_0) [custom_components.youfone.client] [YoufoneClient|login|start]
2023-08-16 12:06:44.129 DEBUG (SyncWorker_0) [custom_components.youfone.client] [YoufoneClient|login|authenticate] Calling POST https://my.youfone.nl/prov/MyYoufone/MyYOufone.Wcf/v2.0/Service.svc/json/login with {"request": {"Login": "xxxxxxxxx", "Password": "xxxxxxxxx"}}
2023-08-16 12:06:44.176 DEBUG (SyncWorker_0) [custom_components.youfone.client] [YoufoneClient|login|authenticate] http status code = 418 (expecting None)
2023-08-16 12:06:44.176 DEBUG (SyncWorker_0) [custom_components.youfone.client] [YoufoneClient|login|authenticate] Response:

2023-08-16 12:06:44.177 DEBUG (MainThread) [custom_components.youfone.config_flow] Expecting value: line 1 column 1 (char 0)

**Comment by geertmeersman** [comment]
Ha, funny, seems they have "blocked" the calls by sending back the http 418.
Since I don't own a youfone NL account, I can't really test it out :-(
So if someone can play around with the authentication and that knows some python, it would help...

**Comment by Evergorn** [comment]
I don't know much about python so I cannot help. Maybe someone else is able to.

**Comment by rgerbranda** [comment]
Is it possible to run the scripts standalone?

**Comment by rgerbranda** [comment]
Hi @geertmeersman 

I see the same response from my.youfone.be (Belgium server)

```
2023-08-20 21:22:08.012 DEBUG (SyncWorker_2) [custom_components.youfone.client] [YoufoneClient|login|start]
2023-08-20 21:22:08.067 DEBUG (SyncWorker_2) [custom_components.youfone.client] [YoufoneClient|login|authenticate] Calling POST https://my.youfone.be/prov/MyYoufone/MyYOufone.Wcf/v2.0/Service.svc/json/login with {"request": {"Login": "remko", "Password": "adsfaf"}}
2023-08-20 21:22:08.191 DEBUG (SyncWorker_2) [custom_components.youfone.client] [YoufoneClient|login|authenticate] http status code = 418 (expecting None)
2023-08-20 21:22:08.191 DEBUG (SyncWorker_2) [custom_components.youfone.client] [YoufoneClient|login|authenticate] Response:

2023-08-20 21:22:08.193 DEBUG (MainThread) [custom_components.youfone.config_flow] Expecting value: line 1 column 1 (char 0)
```

**Comment by geertmeersman** [comment]
That sounds bad....

**Comment by rgerbranda** [comment]
I did some testing with CURL, login works fine.

Command:
```
curl -H 'Content-Type: application/json' -H 'Referer: https://my.youfone.nl/login' \
     -d '{"request": {"Login": "x@y.nl","Password": "abcd123"}}' \
     -vv https://my.youfone.nl/prov/MyYoufone/MyYOufone.Wcf/v2.0/Service.svc/json/login \
```

The response headers include a ```securitykey```

The JSON response is fine

```
{"Message":"Authorization succes","ResultCode":0,"Object":{ ....... }}
```

**Comment by rgerbranda** [comment]
I tried the same with Python ```requests``` and ```urllib.request```, but I'm stuck on an error that I cannot solve.

```
import requests

headers = {
    'Referer': 'https://my.youfone.nl/login',
}

data = {
    'request': {
        'Login': 'x@y.nl',
        'Password': 'df'
    }
}

url = 'https://my.youfone.nl/prov/MyYoufone/MyYOufone.Wcf/v2.0/Service.svc/json/login'

req = requests.post(url, json=data, headers=headers)

print(req.status_code)
print(req.text)
```

Result:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/idlelib/run.py", line 578, in runcode
    exec(code, self.locals)
  File "/home/rrr/youfone/request.py", line 16, in <module>
    req = requests.post(url, json=data, headers=headers)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 544, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 657, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by geertmeersman** [comment]
I indeed have now the same issues on the BE server too. I'll check tomorrow on how to solve it.

**Comment by geertmeersman** [comment]
Let me know if it is fixed with the new release :-)

**Comment by rgerbranda** [comment]
Thanks. Did you test this? Because adding the headers ```Origin``` and ```User-Agent``` didn't solve the problem in my test script. I still have error 'Remote end closed connection without response'.

```
import requests

headers = requests.utils.default_headers()

headers.update(
    {
        'Referer': 'https://my.youfone.nl/login',
        'Origin': 'https://my.youfone.nl',
        "User-Agent" : "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
    }
)

data = {
    'request': {
        'Login': 'x@y.nl',
        'Password': 'df'
    }
}

url = 'https://my.youfone.nl/prov/MyYoufone/MyYOufone.Wcf/v2.0/Service.svc/json/login'

req = requests.post(url, json=data, allow_redirects=True,headers=headers)

print(req.status_code)
print(req.text)
```

**Comment by geertmeersman** [comment]
I did not test your code, as you are using requests, which is not http2 compliant. Youfone requires http2, so you need to use httpx.

I tested it on my BE account and all works again

**Comment by rgerbranda** [comment]
Perfect! It works again :-)

**Comment by geertmeersman** [comment]
Hooray! And sorry for the delay in fixing it, but returning from holidays is always a bit busy 👍
